version: '3.1'
services:
  pasarela:
    image: pasarela
    build:
        context: ./backend-arso
        dockerfile: Dockerfile-Pasarela
    restart: always
    ports:
      - '8090:8090'
    environment:
      zuul.routes.restaurantes.path : '/restaurantes/**'
      zuul.routes.restaurantes.url : 'http://restaurantes-rest:8080/api/restaurantes'
      zuul.routes.opiniones.path : '/opiniones/**'
      zuul.routes.opiniones.url : 'http://opiniones-rest:5204/api/opiniones'
      URI_MONGODB: 'mongodb+srv://arso-ag-rl:wetsek-3quvji-naNsah@cluster0.h4apf4g.mongodb.net/?retryWrites=true&w=majority'
      
  usuarios-rest:
    image: usuarios
    build:
        context: ./backend-arso
        dockerfile: Dockerfile-Usuarios
    restart: always
    ports:
      - '8081:8080'
    environment:
      URI_MONGODB: 'mongodb+srv://arso-ag-rl:wetsek-3quvji-naNsah@cluster0.h4apf4g.mongodb.net/?retryWrites=true&w=majority'

  restaurantes-rest:
    image: restaurantes
    build:
        context: ./backend-arso
        dockerfile: Dockerfile-Restaurantes
    restart: always
    ports:
      - '8080:8080'
    environment:
      URI_MONGODB: 'mongodb+srv://arso-ag-rl:wetsek-3quvji-naNsah@cluster0.h4apf4g.mongodb.net/?retryWrites=true&w=majority'
      
  opiniones-rest:
    image: opiniones
    build:
        context: ./backend-arso/opiniones-rest
        dockerfile: Dockerfile-Opiniones
    restart: always
    ports:
      - '5204:5204'
    environment:
      URI_MONGODB: 'mongodb+srv://arso-ag-rl:wetsek-3quvji-naNsah@cluster0.h4apf4g.mongodb.net/?retryWrites=true&w=majority'

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'Incidencias'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  node-server:
    image: node
    build:
        context: .
        dockerfile: Dockerfile-Node
    depends_on:
      - mysql
    restart: always
    ports:
      - '3000:3000'
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: Incidencias
    links:
      - mysql
volumes:
  mysql_data: