# Debe construirse desde la carpeta que contiene a los dos proyectos
# Por ejemplo: docker build -t bookle-rest:v2 -f bookle-rest/Dockerfile-2 .
FROM maven:3.8.5-jdk-11 AS builder

WORKDIR /app-base/
COPY usuarios-pasarela/pom.xml .
RUN mvn -e -B dependency:resolve
COPY usuarios-pasarela/src ./src
RUN mvn install

WORKDIR /app/
COPY pasarela/pom.xml .
RUN mvn -e -B dependency:resolve
COPY pasarela/src ./src
RUN mvn package

FROM tomcat:9.0.58-jdk11
WORKDIR /usr/local/tomcat/webapps/
COPY --from=builder /app/target/pasarela-0.0.1-SNAPSHOT.jar ROOT.jar

EXPOSE 8090
CMD ["java", "-jar", "ROOT.jar"]